server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # Active la localisation des routes via Eureka
          lower-case-service-id: false # Noms des services en minuscules
    loadbalancer:
      retry:
        enabled: true    # Réessayer en cas d'échec

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true